-- BT1 
SELECT MaLoaiPhong, TenLoaiPhong, DonGia
FROM LOAI_PHONG
WHERE DonGia > (SELECT AVG(DonGia) FROM LOAI_PHONG);

-- BT2 
SELECT MaDV, TenDV, DonGia
FROM DICH_VU
WHERE DonGia = (SELECT MAX(DonGia) FROM DICH_VU);

-- BT3
SELECT KH.MaKH, KH.HoTen, DV.TenDV, DV.DonGia
FROM KHACH_HANG KH
INNER JOIN DAT_PHONG DP
ON DP.MaKH = KH.MaKH
INNER JOIN SU_DUNG_DV SD
ON SD.MaDatPhong = DP.MaDatPhong
INNER JOIN DICH_VU DV 
ON DV.MaDV = SD.MaDV
WHERE DV.DonGia = (SELECT MAX(DonGia) FROM DICH_VU);

-- BT4 
SELECT KH.MaKH, KH.HoTen, P.SoPhong, LP.TenLoaiPhong, LP.DonGia
FROM KHACH_HANG KH
INNER JOIN DAT_PHONG DP
ON DP.MaKH = KH.MaKH
INNER JOIN PHONG P 
ON DP.MaPhong = P.MaPhong 
INNER JOIN LOAI_PHONG LP
ON LP.MaLoaiPhong = P.MaLoaiPhong
WHERE LP.DonGia = (SELECT MAX(DonGia) FROM LOAI_PHONG);

-- BT5
SELECT DISTINCT KH.MaKH, KH.HoTen, KH.DienThoai
FROM KHACH_HANG KH
INNER JOIN DAT_PHONG DP
ON DP.MaKH = KH.MaKH
INNER JOIN PHONG P 
ON DP.MaPhong = P.MaPhong 
INNER JOIN LOAI_PHONG LP
ON LP.MaLoaiPhong = P.MaLoaiPhong
WHERE LP.SoNguoiToiDa IN (
	SELECT SoNguoiToiDa
	FROM LOAI_PHONG
	WHERE SoNguoiToiDa >=3
);

-- BT6
SELECT KH.MaKH, KH.HoTen, LP.TenLoaiPhong
FROM KHACH_HANG KH
INNER JOIN DAT_PHONG DP
ON DP.MaKH = KH.MaKH
INNER JOIN PHONG P 
ON DP.MaPhong = P.MaPhong 
INNER JOIN LOAI_PHONG LP
ON LP.MaLoaiPhong = P.MaLoaiPhong
WHERE LP.MaLoaiPhong IN (
	SELECT LP.MaLoaiPhong
	FROM KHACH_HANG KH
	INNER JOIN DAT_PHONG DP
	ON DP.MaKH = KH.MaKH
	INNER JOIN PHONG P 
	ON DP.MaPhong = P.MaPhong 
	INNER JOIN LOAI_PHONG LP
	ON LP.MaLoaiPhong = P.MaLoaiPhong
	WHERE KH.MaKH = 'KH01'
) AND KH.MaKH <> 'KH01'
;

-- BT7
SELECT DISTINCT DV.MaDV, DV.TenDV, DV.DonGia
FROM DICH_VU DV
WHERE DV.MaDV NOT IN (
	SELECT DISTINCT MaDV
	FROM SU_DUNG_DV
	WHERE NgaySuDung BETWEEN '2026-09-01' AND '2026-09-30'
);

-- BT8 
SELECT KH.MaKH, KH.HoTen, KH.DienThoai
FROM KHACH_HANG KH
WHERE KH.MaKH NOT IN (
	SELECT KH.MaKH 
	FROM KHACH_HANG KH
	INNER JOIN DAT_PHONG DP
	ON DP.MaKH = KH.MaKH
	INNER JOIN SU_DUNG_DV SD
	ON SD.MaDatPhong = DP.MaDatPhong
	INNER JOIN DICH_VU DV 
	ON DV.MaDV = SD.MaDV
	WHERE DV.DonGia > (SELECT AVG(DonGia) FROM DICH_VU)
);

-- BT9
SELECT DISTINCT KH.MaKH, KH.HoTen, KH.DienThoai
FROM KHACH_HANG KH
WHERE EXISTS (
	SELECT * FROM DAT_PHONG DP
	INNER JOIN SU_DUNG_DV SD
	ON SD.MaDatPhong = DP.MaDatPhong
	WHERE DP.MaKH = KH.MaKH
);

-- BT10
SELECT DISTINCT MaLoaiPhong, TenLoaiPhong, DonGia, SoNguoiToiDa
FROM LOAI_PHONG 
WHERE EXISTS (
	SELECT *
	FROM KHACH_HANG KH
	INNER JOIN DAT_PHONG DP
	ON DP.MaKH = KH.MaKH
	INNER JOIN PHONG P 
	ON DP.MaPhong = P.MaPhong 
	WHERE LOAI_PHONG.MaLoaiPhong = P.MaLoaiPhong
);

-- BT11
SELECT DISTINCT MaKH, HoTen, DienThoai
FROM KHACH_HANG KH
WHERE EXISTS (
	SELECT *
	FROM DAT_PHONG DP
	INNER JOIN SU_DUNG_DV SD
	ON SD.MaDatPhong = DP.MaDatPhong
	INNER JOIN DICH_VU DV 
	ON DV.MaDV = SD.MaDV
	WHERE DP.MaKH = KH.MaKH
	AND KH.HoTen LIKE 'Nguyen%' AND SD.SoLuong >= 3 
);

-- BT12
SELECT DISTINCT KH.MaKH, KH.HoTen, KH.DienThoai
FROM KHACH_HANG KH
WHERE NOT EXISTS (
	SELECT *
	FROM DAT_PHONG DP
	INNER JOIN SU_DUNG_DV SD
	ON SD.MaDatPhong = DP.MaDatPhong
	INNER JOIN DICH_VU DV 
	ON DV.MaDV = SD.MaDV
	WHERE KH.MaKH = DP.MaKH
) AND EXISTS (
	SELECT * 
	FROM DAT_PHONG DP2
	WHERE DP2.MaKH = KH.MaKH
);

-- BT13 
SELECT DISTINCT P.MaPhong, P.SoPhong, LP.TenLoaiPhong
FROM PHONG P 
INNER JOIN LOAI_PHONG LP 
ON LP.MaLoaiPhong = P.MaLoaiPhong
WHERE NOT EXISTS (
	SELECT *
	FROM DAT_PHONG
	WHERE DAT_PHONG.MaPhong = P.MaPhong
);

-- BT14 
SELECT DISTINCT KH.MaKH, KH.HoTen, KH.DienThoai
FROM KHACH_HANG KH
WHERE NOT EXISTS (
	SELECT * 
	FROM DICH_VU
	INNER JOIN DAT_PHONG DP
	ON DP.MaKH = KH.MaKH
	INNER JOIN SU_DUNG_DV SD
	ON SD.MaDatPhong = DP.MaDatPhong
	WHERE DICH_VU.MaDV = SD.MaDV AND DICH_VU.MaDV = 'DV04'
) AND EXISTS (
	SELECT * 
	FROM DAT_PHONG DP2
	WHERE DP2.MaKH = KH.MaKH
);

-- BT15 
SELECT MaLoaiPhong, TenLoaiPhong, DonGia, SoNguoiToiDa
FROM LOAI_PHONG LP
WHERE DonGia > (SELECT AVG(DonGia) FROM LOAI_PHONG)
	AND NOT EXISTS (
	SELECT * 
	FROM PHONG P
	INNER JOIN DAT_PHONG DP
	ON DP.MaPhong = P.MaPhong
	WHERE P.MaLoaiPhong = LP.MaLoaiPhong
);

-- BT16 
SELECT KH.MaKH, KH.HoTen, SUM(SD.SoLuong) AS TONGSOLUONGDV
FROM KHACH_HANG KH
INNER JOIN DAT_PHONG DP
ON DP.MaKH = KH.MaKH
INNER JOIN SU_DUNG_DV SD
ON SD.MaDatPhong = DP.MaDatPhong
GROUP BY KH.MaKH, KH.HoTen
HAVING SUM(SD.SoLuong) >= 5 
AND NOT EXISTS(
	SELECT * 
	FROM DAT_PHONG DP2 
	INNER JOIN SU_DUNG_DV SD2
	ON SD2.MaDatPhong = DP2.MaDatPhong
	WHERE DP2.MaKH = KH.MaKH AND SD2.MaDV = 'DV04'
); 

-- BT17 
SELECT KH.MaKH, KH.HoTen, DV.TenDV, DV.DonGia
FROM KHACH_HANG KH 
INNER JOIN DAT_PHONG DP
ON DP.MaKH = KH.MaKH
INNER JOIN SU_DUNG_DV SD
ON SD.MaDatPhong = DP.MaDatPhong
INNER JOIN DICH_VU DV 
ON DV.MaDV = SD.MaDV
WHERE DV.DonGia > (SELECT AVG(DonGia) FROM DICH_VU)
ORDER BY KH.MaKH ASC
;

-- BT18 
-- NV1
SELECT KH.MaKH, KH.HoTen, KH.DienThoai
    ,COUNT(DP.MaDatPhong) AS TongSo
FROM KHACH_HANG KH
INNER JOIN DAT_PHONG DP
ON KH.MaKH = DP.MaKH
GROUP BY KH.MaKH, KH.HoTen, KH.DienThoai
HAVING COUNT(dp.MaDatPhong) > (
    SELECT AVG(BangThongKe.SoLan)
    FROM (
        SELECT COUNT(MaDatPhong) AS SoLan
        FROM DAT_PHONG
        GROUP BY MaKH
    ) AS BangThongKe
)
ORDER BY TongSo DESC;

-- NV2
SELECT SD.MaSuDung, SD.MaDatPhong, DV.TenDV, SD.NgaySuDung,SD.SoLuong
FROM SU_DUNG_DV SD
INNER JOIN DICH_VU DV
ON SD.MaDV = DV.MaDV
WHERE SD.SoLuong > (
    SELECT AVG(SD2.SoLuong * 1.0)
    FROM SU_DUNG_DV SD2
    WHERE SD2.MaDV = SD.MaDV
)
ORDER BY DV.TenDV, SD.SoLuong DESC;
