USE QL_KHACHSAN;
GO 

-- BT1
SELECT DAT_PHONG.MaDatPhong, KHACH_HANG.MaKH, 
	KHACH_HANG.HoTen, DAT_PHONG.TrangThai
FROM DAT_PHONG
INNER JOIN KHACH_HANG
ON DAT_PHONG.MaKH = KHACH_HANG.MaKH
ORDER BY DAT_PHONG.MaDatPhong ASC;

-- BT2
SELECT KHACH_HANG.MaKH, KHACH_HANG.HoTen, 
	DAT_PHONG.MaDatPhong, PHONG.MaPhong,
	DAT_PHONG.NgayNhan
FROM KHACH_HANG
INNER JOIN DAT_PHONG
ON KHACH_HANG.MaKH = DAT_PHONG.MaKH
INNER JOIN PHONG
ON DAT_PHONG.MaPhong = PHONG.MaPhong
;

-- BT3
SELECT DAT_PHONG.MaDatPhong, KHACH_HANG.HoTen,
	PHONG.SoPhong, LOAI_PHONG.TenLoaiPhong,
	LOAI_PHONG.DonGia, DAT_PHONG.TrangThai
FROM KHACH_HANG
INNER JOIN DAT_PHONG
ON KHACH_HANG.MaKH = DAT_PHONG.MaKH
INNER JOIN PHONG
ON DAT_PHONG.MaPhong = PHONG.MaPhong
INNER JOIN LOAI_PHONG
ON LOAI_PHONG.MaLoaiPhong = PHONG.MaLoaiPhong
;

-- BT4
SELECT KHACH_HANG.HoTen, PHONG.SoPhong,
	LOAI_PHONG.TenLoaiPhong, DAT_PHONG.NgayNhan,
	DAT_PHONG.NgayTra
FROM KHACH_HANG
INNER JOIN DAT_PHONG
ON DAT_PHONG.MaKH = KHACH_HANG.MaKH
INNER JOIN PHONG
ON DAT_PHONG.MaPhong = PHONG.MaPhong
INNER JOIN LOAI_PHONG
ON PHONG.MaLoaiPhong = LOAI_PHONG.MaLoaiPhong
WHERE DAT_PHONG.TrangThai = 'Da dat'
ORDER BY DAT_PHONG.NgayNhan ASC
;

-- BT5
SELECT KHACH_HANG.MaKH, KHACH_HANG.HoTen,
	DAT_PHONG.MaDatPhong, DAT_PHONG.MaPhong,
	DAT_PHONG.TrangThai
FROM KHACH_HANG
LEFT JOIN DAT_PHONG
ON KHACH_HANG.MaKH = DAT_PHONG.MaKH 
;

-- BT6
SELECT PHONG.MaPhong, PHONG.SoPhong,
	DAT_PHONG.MaDatPhong, KHACH_HANG.MaKH,
	DAT_PHONG.TrangThai
FROM DAT_PHONG
INNER JOIN KHACH_HANG
ON KHACH_HANG.MaKH = DAT_PHONG.MaKH
RIGHT JOIN PHONG
ON DAT_PHONG.MaPhong = PHONG.MaPhong
;

-- BT7
SELECT PHONG.MaPhong, PHONG.SoPhong,
	PHONG.TrangThai
FROM DAT_PHONG
RIGHT JOIN PHONG
ON DAT_PHONG.MaPhong = PHONG.MaPhong
WHERE DAT_PHONG.MaDatPhong IS NULL
;

-- BT8 
-- Từ "và" trong bài tập thì sẽ được hiểu với ý nghĩa là tất cả các phòng trống và chưa từng được đặt
SELECT PHONG.MaPhong, PHONG.SoPhong,
	PHONG.TrangThai
FROM DAT_PHONG
RIGHT JOIN PHONG
ON DAT_PHONG.MaPhong = PHONG.MaPhong
WHERE DAT_PHONG.MaDatPhong IS NULL OR PHONG.TrangThai = 'Trong'
ORDER BY PHONG.SoPhong ASC
;

-- BT9
SELECT DK1.MaDatPhong MaDatPhong1,
	DK2.MaDatPhong MaDatPhong2,
	DK1.MaPhong,
	KH1.MaKH MaKH1,
	KH2.MaKH MaKH2
FROM DAT_PHONG DK1
INNER JOIN DAT_PHONG DK2 
ON DK1.MaKH <> DK2.MaKH AND DK1.MaPhong = DK2.MaPhong
INNER JOIN KHACH_HANG KH1
ON DK1.MaKH = KH1.MaKH
INNER JOIN KHACH_HANG KH2
ON DK2.MaKH = KH2.MaKH
;

-- BT10
SELECT DK1.MaDatPhong MaDatPhong1,
	DK2.MaDatPhong MaDatPhong2,
	DK1.MaPhong,
	KH1.MaKH MaKH1,
	KH2.MaKH MaKH2
FROM DAT_PHONG DK1
INNER JOIN DAT_PHONG DK2
ON DK1.MaKH < DK2.MaKH AND DK1.MaPhong = DK2.MaPhong
INNER JOIN KHACH_HANG KH1
ON DK1.MaKH = KH1.MaKH
INNER JOIN KHACH_HANG KH2
ON DK2.MaKH = KH2.MaKH
;
-- Vì nếu sử dụng '<' thì SQL sẽ 
-- hiểu được rằng là user đang muốn so sánh theo dạng chuỗi 

-- BT11
SELECT KHACH_HANG.HoTen
FROM KHACH_HANG
INNER JOIN DAT_PHONG
ON DAT_PHONG.MaKH = KHACH_HANG.MaKH
INNER JOIN PHONG 
ON DAT_PHONG.MaPhong = PHONG.MaPhong
INNER JOIN LOAI_PHONG
ON LOAI_PHONG.MaLoaiPhong = PHONG.MaLoaiPhong
WHERE LOAI_PHONG.MaLoaiPhong = 'LP01'
UNION 
SELECT KHACH_HANG.HoTen
FROM KHACH_HANG
INNER JOIN DAT_PHONG
ON DAT_PHONG.MaKH = KHACH_HANG.MaKH
INNER JOIN PHONG 
ON DAT_PHONG.MaPhong = PHONG.MaPhong
INNER JOIN LOAI_PHONG
ON LOAI_PHONG.MaLoaiPhong = PHONG.MaLoaiPhong
WHERE LOAI_PHONG.MaLoaiPhong = 'LP02'
;

-- BT12
SELECT KHACH_HANG.HoTen
FROM KHACH_HANG
INNER JOIN DAT_PHONG
ON DAT_PHONG.MaKH = KHACH_HANG.MaKH
INNER JOIN PHONG 
ON DAT_PHONG.MaPhong = PHONG.MaPhong
INNER JOIN LOAI_PHONG
ON LOAI_PHONG.MaLoaiPhong = PHONG.MaLoaiPhong
WHERE LOAI_PHONG.MaLoaiPhong = 'LP01' 
INTERSECT
SELECT KHACH_HANG.HoTeN
FROM KHACH_HANG
INNER JOIN DAT_PHONG
ON DAT_PHONG.MaKH = KHACH_HANG.MaKH
INNER JOIN PHONG 
ON DAT_PHONG.MaPhong = PHONG.MaPhong
INNER JOIN LOAI_PHONG
ON LOAI_PHONG.MaLoaiPhong = PHONG.MaLoaiPhong
WHERE LOAI_PHONG.MaLoaiPhong = 'LP03'
;

-- BT13
SELECT KHACH_HANG.HoTen
FROM KHACH_HANG
INNER JOIN DAT_PHONG
ON DAT_PHONG.MaKH = KHACH_HANG.MaKH
INNER JOIN PHONG 
ON DAT_PHONG.MaPhong = PHONG.MaPhong
INNER JOIN LOAI_PHONG
ON LOAI_PHONG.MaLoaiPhong = PHONG.MaLoaiPhong
WHERE LOAI_PHONG.MaLoaiPhong = 'LP02' 
EXCEPT
SELECT KHACH_HANG.HoTeN
FROM KHACH_HANG
INNER JOIN DAT_PHONG
ON DAT_PHONG.MaKH = KHACH_HANG.MaKH
INNER JOIN PHONG 
ON DAT_PHONG.MaPhong = PHONG.MaPhong
INNER JOIN LOAI_PHONG
ON LOAI_PHONG.MaLoaiPhong = PHONG.MaLoaiPhong
WHERE LOAI_PHONG.MaLoaiPhong = 'LP04'
;

-- BT14
SELECT  DP.MaDatPhong, 
		KH.HoTen,
		P.SoPhong, 
		LP.TenLoaiPhong, 
		DP.NgayNhan, 
		DP.NgayTra,
		DP.TrangThai
FROM  DAT_PHONG DP
INNER JOIN  PHONG P ON P.MaPhong = DP. MaPhong
INNER JOIN KHACH_HANG KH ON DP.MaKH = KH.MaKH
INNER JOIN LOAI_PHONG LP ON LP.MaLoaiPhong = P.MaLoaiPhong
WHERE DP.NgayNhan >= '2026-08-20'
ORDER By DP.NgayNhan DESC;

-- BT15 
-- Nghiệp vụ tự chọn 
SELECT KHACH_HANG.HoTen
FROM KHACH_HANG
INNER JOIN DAT_PHONG
ON DAT_PHONG.MaKH = KHACH_HANG.MaKH
INNER JOIN PHONG 
ON DAT_PHONG.MaPhong = PHONG.MaPhong
INNER JOIN LOAI_PHONG
ON LOAI_PHONG.MaLoaiPhong = PHONG.MaLoaiPhong
WHERE LOAI_PHONG.MaLoaiPhong = 'LP02' 
ORDER BY KHACH_HANG.HoTen DESC
;

