-- BT1 + 2 + 3. Tạo Bảng 
-- Phần này đã có ở database_qlkhachsan nên phần exercise này sẽ được bỏ qua phần kia 
-- Thêm table SU_DUNG_DV

-- BT4: 
SELECT COUNT(*) 
FROM SU_DUNG_DV;

-- BT5: 
SELECT SUM(SoLuong)
FROM SU_DUNG_DV;

-- BT6: 
SELECT AVG(SoLuong)
FROM SU_DUNG_DV;

-- BT7: 
SELECT MIN(DonGia) AS NHONHAT, MAX(DonGia) AS LONNHAT
FROM DICH_VU;

-- BT8: 
SELECT MIN(NgaySuDung) AS NHONHAT, MAX(NgaySuDung) AS LONNHAT
FROM SU_DUNG_DV;

-- BT9: 
SELECT LP.MaLoaiPhong, LP.TenLoaiPhong, COUNT(P.SoPhong) AS SoLuongPhong
FROM LOAI_PHONG LP
INNER JOIN PHONG P
ON P.MaLoaiPhong = LP.MaLoaiPhong
GROUP BY LP.MaLoaiPhong, LP.TenLoaiPhong
;

-- BT10: 
SELECT KH.MaKH, KH.HoTen, COUNT(MaDatPhong) AS SoLuongPhieu
FROM KHACH_HANG KH
INNER JOIN DAT_PHONG
ON DAT_PHONG.MaKH = KH.MaKH
GROUP BY KH.MaKH, KH.HoTen
;

-- BT11: 
SELECT DV.MaDV, DV.TenDV, COUNT(SD.MaSuDung) AS SoLanDV, SUM(SD.SoLuong) AS TongSoLuong
FROM DICH_VU DV
INNER JOIN SU_DUNG_DV SD
ON DV.MaDV = SD.MaDV
GROUP BY DV.MaDV, DV.TenDV
;

-- BT12: 
SELECT DP.MaDatPhong, COUNT(SD.MaSuDung) AS SoLanDV, SUM(SD.SoLuong) AS TongSoLuong
FROM DAT_PHONG DP
INNER JOIN SU_DUNG_DV SD
ON SD.MaDatPhong = DP.MaDatPhong
GROUP BY DP.MaDatPhong
;

-- BT13: 
SELECT KH.MaKH, KH.HoTen, SUM(SD.SoLuong*DV.DonGia) AS TONGTIENSUDUNG
FROM KHACH_HANG KH
INNER JOIN DAT_PHONG DP
ON DP.MaKH = KH.MaKH
INNER JOIN SU_DUNG_DV SD
ON SD.MaDatPhong = DP.MaDatPhong
INNER JOIN DICH_VU DV 
ON DV.MaDV = SD.MaDV
GROUP BY KH.MaKH, KH.HoTen
ORDER BY KH.MaKH
;

-- BT14: 
SELECT SD.MaDV, DV.TenDV, SUM(SD.SoLuong) AS SOLUONGSD
FROM SU_DUNG_DV SD
INNER JOIN DICH_VU DV
ON DV.MaDV = SD.MaDV
WHERE SD.NgaySuDung BETWEEN '2026-08-01' AND '2026-08-31'
GROUP BY SD.MaDV, DV.TenDV
;

-- BT15: 
SELECT DV.MaDV, DV.TenDV, SUM(SD.SoLuong) AS SOLUONGSUDUNG
FROM KHACH_HANG KH 
INNER JOIN DAT_PHONG DP
ON DP.MaKH  = KH.MaKH
INNER JOIN SU_DUNG_DV SD
ON DP.MaDatPhong = SD.MaDatPhong
INNER JOIN DICH_VU DV 
ON DV.MaDV = SD.MaDV
WHERE KH.HoTen LIKE 'Nguyen%'
GROUP BY DV.MaDV, DV.TenDV
;

-- BT16: 
SELECT LP.MaLoaiPhong, LP.TenLoaiPhong, COUNT(DP.MaDatPhong) AS SOLUONGDATPHONG
FROM LOAI_PHONG LP
INNER JOIN PHONG P 
ON P.MaLoaiPhong = LP.MaLoaiPhong
INNER JOIN DAT_PHONG DP 
ON P.MaPhong = DP.MaPhong
WHERE LP.MaLoaiPhong BETWEEN 'LP03' AND 'LP05'
GROUP BY LP.MaLoaiPhong, LP.TenLoaiPhong
;

-- BT17: 
SELECT DV.MaDV, DV.TenDV, COUNT(SD.SoLuong) AS SOLUONGSUDUNG
FROM KHACH_HANG KH 
INNER JOIN DAT_PHONG DP
ON DP.MaKH  = KH.MaKH
INNER JOIN SU_DUNG_DV SD
ON DP.MaDatPhong = SD.MaDatPhong
INNER JOIN DICH_VU DV 
ON DV.MaDV = SD.MaDV
GROUP BY DV.MaDV, DV.TenDV
HAVING COUNT(SD.SoLuong) >= 5
;

-- BT18:
SELECT KH.MaKH, KH.HoTen, COUNT(MaDatPhong) AS SoLuongPhieu
FROM KHACH_HANG KH
INNER JOIN DAT_PHONG
ON DAT_PHONG.MaKH = KH.MaKH
GROUP BY KH.MaKH, KH.HoTen
HAVING COUNT(MaDatPhong) >= 2
;

-- BT19: 
SELECT DV.MaDV, DV.TenDV, SUM(SD.SoLuong) AS TongSoLuong
FROM DICH_VU DV
INNER JOIN SU_DUNG_DV SD
ON DV.MaDV = SD.MaDV
GROUP BY DV.MaDV, DV.TenDV
HAVING SUM(SD.SoLuong) >= 8
;


-- BT20: 
SELECT KH.MaKH, KH.HoTen, SUM(SD.SoLuong*DV.DonGia) AS TONGTIENSUDUNG
FROM KHACH_HANG KH
INNER JOIN DAT_PHONG DP
ON DP.MaKH = KH.MaKH
INNER JOIN SU_DUNG_DV SD
ON SD.MaDatPhong = DP.MaDatPhong
INNER JOIN DICH_VU DV 
ON DV.MaDV = SD.MaDV
GROUP BY KH.MaKH, KH.HoTen
HAVING SUM(SD.SoLuong*DV.DonGia) >= 500000
ORDER BY KH.MaKH ASC
;

-- BT21: 
SELECT KH.MaKH, KH.HoTen, COUNT(SD.MaSuDung) AS SOLANSD ,SUM(SD.SoLuong) AS SOLUONGSDDV, MAX(SD.NgaySuDung)
FROM KHACH_HANG KH
INNER JOIN DAT_PHONG DP
ON DP.MaKH = KH.MaKH
INNER JOIN SU_DUNG_DV SD
ON SD.MaDatPhong = DP.MaDatPhong
INNER JOIN DICH_VU DV 
ON DV.MaDV = SD.MaDV
WHERE SD.NgaySuDung >= '2026-09-01'
GROUP BY KH.MaKH, KH.HoTen
HAVING COUNT(SD.MaSuDung) >= 2
;

-- BT22: 
SELECT KH.MaKH, KH.HoTen, DV.TenDV, SUM(SD.SoLuong) AS TONGSOLANSD,SUM(SD.SoLuong*DV.DonGia) AS TONGTIENSUDUNG
FROM KHACH_HANG KH
INNER JOIN DAT_PHONG DP
ON DP.MaKH = KH.MaKH
INNER JOIN SU_DUNG_DV SD
ON SD.MaDatPhong = DP.MaDatPhong
INNER JOIN DICH_VU DV 
ON DV.MaDV = SD.MaDV
GROUP BY KH.MaKH, KH.HoTen, DV.DonGia, DV.TenDV
HAVING SUM(SD.SoLuong) >= 3
;

-- BT23:
SELECT LP.MaLoaiPhong, LP.TenLoaiPhong, COUNT(DISTINCT DP.MaDatPhong) AS SOLUONGDATPHONG, COUNT(SD.MaSuDung) AS SOLANSD, SUM(SD.SoLuong) AS TONGSOLUONG
FROM LOAI_PHONG LP
INNER JOIN PHONG P 
ON P.MaLoaiPhong = LP.MaLoaiPhong
INNER JOIN DAT_PHONG DP 
ON P.MaPhong = DP.MaPhong
INNER JOIN SU_DUNG_DV SD 
ON SD.MaDatPhong = DP.MaDatPhong
WHERE DP.NgayNhan >= '2026-08-20'
GROUP BY LP.MaLoaiPhong, LP.TenLoaiPhong
;

-- BT24: 
SELECT DV.MaDV, DV.TenDV, COUNT(SD.MaSuDung) AS SoLanDV, SUM(SD.SoLuong) AS TongSoLuong, AVG(SD.SoLuong) AS SOLUONGTRUNGBINH
FROM DICH_VU DV
INNER JOIN SU_DUNG_DV SD
ON DV.MaDV = SD.MaDV
WHERE SD.NgaySuDung >= '2026-08-20' 
GROUP BY DV.MaDV, DV.TenDV
HAVING SUM(SD.SoLuong) >= 5
;

-- BT25: 
SELECT LP.MaLoaiPhong, LP.TenLoaiPhong, COUNT(DP.MaKH) AS SOLUONGKHACH
FROM LOAI_PHONG LP
INNER JOIN PHONG P
ON LP.MaLoaiPhong = P.MaLoaiPhong
INNER JOIN DAT_PHONG DP 
ON P.MaPhong = DP.MaPhong
WHERE YEAR(DP.NgayNhan) = 2026
GROUP BY LP.MaLoaiPhong, LP.TenLoaiPhong
;

SELECT DV.MaDV, DV.TenDV, COUNT(SD.MaSuDung) AS SoLanDV, SUM(SD.SoLuong) AS TongSoLuong
FROM DICH_VU DV
INNER JOIN SU_DUNG_DV SD
ON DV.MaDV = SD.MaDV
GROUP BY DV.MaDV, DV.TenDV
;