-- BT1: 
CREATE PROCEDURE KH_DAT_PHONG
AS 
BEGIN 
	SELECT 'TONG SO KHACH HANG DA TUNG DAT PHONG' AS NOIDUNG, COUNT(DISTINCT MaKH) AS SOLUONG 
	FROM DAT_PHONG ; 

	SELECT KH.MaKH, KH.HoTen, KH.DienThoai
	FROM KHACH_HANG KH 
	WHERE EXISTS (
		SELECT * 
		FROM DAT_PHONG DP 
		WHERE DP.MaKH = KH.MaKH
	);
END;
GO

-- BT2: 
CREATE PROCEDURE KHAI_THAC_PHONG
AS 
BEGIN 
-- Bài tập này được hiểu là tổng số phòng đã được đặt có nghĩa là các phòng riêng biệt -> distinct
	SELECT 'TONG SO PHONG DA TUNG DAT' AS NOIDUNG, COUNT(DISTINCT MaPhong) AS TONGSOPHONG
	FROM DAT_PHONG;

	SELECT P.MaPhong, P.SoPhong, LP.TenLoaiPhong
	FROM PHONG P
	INNER JOIN LOAI_PHONG LP
	ON LP.MaLoaiPhong = P.MaLoaiPhong
	WHERE EXISTS (
		SELECT * 
		FROM DAT_PHONG DP 
		WHERE DP.MaPhong = P.MaPhong
	);
END;
GO

-- BT3: 
CREATE PROCEDURE TH_SU_DUNG_DV
AS 
BEGIN 
	SELECT COUNT(MaDV) AS SOLANSD, SUM(SoLuong) AS SOLUONGSD
	FROM SU_DUNG_DV; 
	
	SELECT DV.MaDV, DV.TenDV
		,COUNT(SD.MaDV) AS SOLANSUDUNG
		,SUM(SD.SoLuong) AS TONGSOLUONGSD
	FROM DICH_VU DV 
	INNER JOIN SU_DUNG_DV SD 
	ON SD.MaDV = DV.MaDV
	GROUP BY DV.MaDV, DV.TenDV;
END;
GO

-- BT4: 
CREATE PROCEDURE KHAI_THAC_DV
AS 
BEGIN
	SELECT COUNT(DISTINCT SD.MaDV) AS SOLUONGDICHVU_DATUNGSD, SUM(SD.SoLuong*DV.DonGia) AS TONGSOTIENPHATSINH
	FROM SU_DUNG_DV SD 
	INNER JOIN DICH_VU DV
	ON SD.MaDV = DV.MaDV;
	
	SELECT DV.MaDV, DV.TenDV, 
		SUM(SD.SoLuong) AS TONGSOLUONGSD, SUM(SD.SoLuong * DV.DonGia) AS TONGTIENDICHVU
	FROM DICH_VU DV 
	INNER JOIN SU_DUNG_DV SD 
	ON SD.MaDV = DV.MaDV
	GROUP BY DV.MaDV, DV.TenDV
	HAVING SUM(SD.SoLuong * DV.DonGia) >= 500000;
END;
GO

-- BT5: 
CREATE PROCEDURE TH_DP @MAKH VARCHAR(10)
AS 
BEGIN 
	SELECT 'TONG SO PHIEU DP' AS NOIDUNG
		, COUNT(MaDatPhong) AS SOPHIEUDAT
	FROM DAT_PHONG
	WHERE MaKH = @MAKH;

	SELECT DP.MaDatPhong, P.SoPhong, LP.TenLoaiPhong, DP.NgayNhan, DP.NgayTra, DP.TrangThai
	FROM DAT_PHONG DP 
	INNER JOIN PHONG P 
	ON DP.MaPhong = P.MaPhong
	INNER JOIN LOAI_PHONG LP 
	ON LP.MaLoaiPhong = P.MaLoaiPhong
	WHERE DP.MaKH = @MAKH
END;
GO

-- BT6: 
CREATE PROCEDURE TH_LOAIPHONG @MALOAIPHONG VARCHAR(10) 
AS 
BEGIN 
	SELECT 'SO PHONG THUOC LOAI PHONG ' + @MALOAIPHONG AS NOIDUNG,
		COUNT(P.MaPhong) AS SOPHONG
	FROM LOAI_PHONG LP 
	INNER JOIN PHONG P 
	ON LP.MaLoaiPhong = P.MaLoaiPhong
	WHERE LP.MaLoaiPhong = @MALOAIPHONG; 

	SELECT P.MaPhong, P.SoPhong, P.TrangThai
	FROM PHONG P 
	INNER JOIN LOAI_PHONG LP
	ON LP.MaLoaiPhong = P.MaLoaiPhong
	WHERE LP.MaLoaiPhong = @MALOAIPHONG; 
END;
GO

-- BT7: 
CREATE PROCEDURE TH_SD_DV @MADV VARCHAR(10)
AS 
BEGIN
	SELECT COUNT(*) AS SOLAN, SUM(SoLuong) AS SOLUONG
	FROM SU_DUNG_DV 
	WHERE MaDV = @MADV;

	SELECT DP.MaDatPhong, KH.MaKH, KH.HoTen, SD.NgaySuDung, SD.SoLuong
	FROM DAT_PHONG DP 
	INNER JOIN SU_DUNG_DV SD 
	ON SD.MaDatPhong = DP.MaDatPhong
	INNER JOIN KHACH_HANG KH 
	ON KH.MaKH = DP.MaKH
	WHERE SD.MaDV = @MADV;
END;
GO


-- BT8: 
CREATE PROCEDURE DV_KHOANGTG @MADV VARCHAR(10), @DATE_BEGIN DATE, @DATE_END DATE
AS 
BEGIN
	SELECT COUNT(*) AS SOLAN, SUM(SoLuong) AS SOLUONG
	FROM SU_DUNG_DV
	WHERE MaDV = @MADV AND NgaySuDung BETWEEN @DATE_BEGIN AND @DATE_END;

	SELECT DP.MaDatPhong, KH.MaKH, KH.HoTen, SD.NgaySuDung, SD.SoLuong
	FROM DAT_PHONG DP
	INNER JOIN KHACH_HANG KH
	ON DP.MaKH = KH.MaKH
	INNER JOIN SU_DUNG_DV SD 
	ON SD.MaDatPhong = DP.MaDatPhong
	WHERE MaDV = @MADV AND SD.NgaySuDung BETWEEN @DATE_BEGIN AND @DATE_END;
END;
GO

-- BT9:
CREATE PROCEDURE LOAI_PHONG_KHOANGTG @MALOAIPHONG VARCHAR(10), @NGAYNHANPHONG_BEGIN DATE, @NGAYNHANPHONG_END DATE
AS 
BEGIN
	SELECT 'SO PHIEU DAT PHONG CUA ' + @MALOAIPHONG + ' TRONG KHOANG ' + CAST (@NGAYNHANPHONG_BEGIN AS VARCHAR(20)) + ' - ' + CAST (@NGAYNHANPHONG_END AS VARCHAR(20)) AS NOIDUNG
		,COUNT(*) AS SOPHIEU
	FROM DAT_PHONG DP 
	INNER JOIN PHONG P 
	ON P.MaPhong = DP.MaPhong
	WHERE P.MaLoaiPhong = @MALOAIPHONG AND NgayNhan BETWEEN @NGAYNHANPHONG_BEGIN AND @NGAYNHANPHONG_END;

	SELECT DP.MaDatPhong, KH.MaKH, KH.HoTen, P.SoPhong, DP.NgayNhan, DP.NgayTra
	FROM DAT_PHONG DP 
	INNER JOIN KHACH_HANG KH 
	ON KH.MaKH = DP.MaKH
	INNER JOIN PHONG P 
	ON P.MaPhong = DP.MaPhong
	WHERE P.MaLoaiPhong = @MALOAIPHONG AND DP.NgayNhan BETWEEN @NGAYNHANPHONG_BEGIN AND @NGAYNHANPHONG_END;
END;
GO

-- BT10: 
CREATE PROCEDURE KH_SUDUNGDV_NGUONG @MADV VARCHAR(10), @SOLUONG_TOITHIEU INT 
AS 
BEGIN 
	SELECT 'SO LAN SU DUNG CUA ' +  @MADV + ' VOI SO LAN TOI THIEU ' + CAST (@SOLUONG_TOITHIEU AS VARCHAR(20)) AS NOIDUNG
		, COUNT(*) SOLAN_DATMUC
	FROM SU_DUNG_DV SD 
	WHERE MaDV = @MADV AND SoLuong >= @SOLUONG_TOITHIEU;

	SELECT KH.MaKH, KH.HoTen, KH.DienThoai
	FROM SU_DUNG_DV SD 
	INNER JOIN DAT_PHONG DP 
	ON DP.MaDatPhong = SD.MaDatPhong
	INNER JOIN KHACH_HANG KH 
	ON KH.MaKH = DP.MaKH
	WHERE SD.MaDV = @MADV AND SD.SoLuong >= @SOLUONG_TOITHIEU;
END;
GO

-- BT11: 
CREATE FUNCTION fn_TONG_SO_KH()
RETURNS INT 
AS 
BEGIN 
	DECLARE @TONG_KH INT; 
	SELECT @TONG_KH = COUNT(*) 
	FROM KHACH_HANG;
	RETURN @TONG_KH;
END;
GO

SELECT dbo.fn_TONG_SO_KH() AS KETQUA_FUNC;
-- TỶ LỆ NGƯỜI CÓ ĐẶT PHÒNG
SELECT ROUND(COUNT(DISTINCT MaKH)/ dbo.fn_TONG_SO_KH() * 100.0, 2) AS TYLEKHACHDATPHONG
FROM DAT_PHONG DP;
GO

-- BT12: 
CREATE FUNCTION fn_SOLAN_DATPHONG(@MAKH VARCHAR(10))
RETURNS INT 
AS 
BEGIN 
	DECLARE @SO_LAN_DAT INT; 
	SELECT @SO_LAN_DAT = COUNT(*)
	FROM DAT_PHONG 
	WHERE MaKH = @MAKH;
	RETURN @SO_LAN_DAT;
END;
GO

-- Danh sách tất cả khách hàng và số lần đặt phòng 
SELECT KH.MaKH, KH.HoTen ,dbo.fn_SOLAN_DATPHONG(KH.MaKH) AS SOLANDATPHONG
FROM KHACH_HANG KH;
GO

SELECT KH.MaKH, KH.HoTen ,dbo.fn_SOLAN_DATPHONG(KH.MaKH) AS SOLANDATPHONG
FROM KHACH_HANG KH
WHERE dbo.fn_SOLAN_DATPHONG(KH.MaKH) >= 2;
GO

-- BT13: 
CREATE FUNCTION fn_TONGTIENDV(@MADATPHONG VARCHAR(10))
RETURNS DECIMAL(12, 2)
AS 
BEGIN 
	DECLARE @TONGTIENDV DECIMAL(12, 2); 
	SELECT @TONGTIENDV = SUM(SD.SoLuong * DV.DonGia)
	FROM SU_DUNG_DV SD 
	INNER JOIN DICH_VU DV 
	ON SD.MaDV = DV.MaDV 
	WHERE @MADATPHONG = SD.MaDatPhong;
	RETURN @TONGTIENDV;
END;
GO

-- Danh sách phiếu đặt phòng kèm tổng tiền dịch vụ 
SELECT DISTINCT DP.MaDatPhong, dbo.fn_TONGTIENDV(DP.MaDatPhong) AS TONGTIENDICHVU
FROM DAT_PHONG DP 
INNER JOIN SU_DUNG_DV SD 
ON DP.MaDatPhong = SD.MaDatPhong;
GO

-- Lọc các phiếu có tổng tiền từ 500000 đồng trở lên 
SELECT DISTINCT DP.MaDatPhong, dbo.fn_TONGTIENDV(DP.MaDatPhong) AS TONGTIENDICHVU
FROM DAT_PHONG DP 
INNER JOIN SU_DUNG_DV SD 
ON DP.MaDatPhong = SD.MaDatPhong
WHERE dbo.fn_TONGTIENDV(DP.MaDatPhong) >= 500000;
GO

-- BT14: 
-- Ở bài tập này thì nếu muốn có một báo cáo đẹp thì có thể dùng hàm dưới đây để lấy:
CREATE FUNCTION fn_SO_NGAY_LUU_TRU_BAOCAO (@MADATPHONG VARCHAR(10))
RETURNS VARCHAR(30)
AS 
BEGIN 
	DECLARE @SO_NGAY_LUU_TRU VARCHAR(30); 
	SELECT @SO_NGAY_LUU_TRU = (
		CASE 
			WHEN DATEDIFF(day, NgayNhan, NgayTra) <= 30 THEN CAST (DATEDIFF(day, NgayNhan, NgayTra) AS VARCHAR(20)) + ' NGAY'
			WHEN DATEDIFF(day, NgayNhan, NgayTra) > 30 THEN CAST ((FLOOR(DATEDIFF(day, NgayNhan, NgayTra) / 30)) AS VARCHAR(20)) + ' THANG ' + CAST ((DATEDIFF(day, NgayNhan, NgayTra) - (FLOOR(DATEDIFF(day, NgayNhan, NgayTra) / 30)) * 30) AS VARCHAR(10)) + ' NGAY'
		END)
	FROM DAT_PHONG
	WHERE MaDatPhong = @MADATPHONG;
	RETURN @SO_NGAY_LUU_TRU;
END;
GO


-- Nếu chỉ muốn định dạng số ngày là kiểu giá trị int thì bên dưới: 
CREATE FUNCTION fn_SO_NGAY_LUU_TRU (@MADATPHONG VARCHAR(10))
RETURNS VARCHAR(30)
AS 
BEGIN 
	DECLARE @SO_NGAY_LUU_TRU VARCHAR(30); 
	SELECT @SO_NGAY_LUU_TRU = DATEDIFF(day, NgayNhan, NgayTra)
	FROM DAT_PHONG
	WHERE MaDatPhong = @MADATPHONG;
	RETURN @SO_NGAY_LUU_TRU;
END;
GO

-- Ý đề bài muốn là lấy số ngày lưu trú * đơn giá. Nên là sẽ lấy câu 19 để hỗ trợ bài 14 này. 
SELECT DP.MaDatPhong, KH.MaKH, DP.NgayNhan, DP.NgayTra, dbo.fn_SO_NGAY_LUU_TRU(DP.MaDatPhong) AS SONGAYLUUTRU, dbo.fn_REVENUE_MDP(DP.MaDatPhong, dbo.fn_SO_NGAY_LUU_TRU(DP.MaDatPhong)) AS TONGTIENPHONG
FROM DAT_PHONG DP 
INNER JOIN KHACH_HANG KH 
ON KH.MaKH = DP.MaKH;
GO

-- BT15: 
CREATE FUNCTION fn_1LAN_SD_DV(@MADV VARCHAR(10), @SOLUONGSUDUNG INT)
RETURNS DECIMAL(12, 2)
AS 
BEGIN 
	DECLARE @THANHTIEN_SD_DV DECIMAL(12, 2); 
	SELECT @THANHTIEN_SD_DV = DonGia * @SOLUONGSUDUNG
	FROM DICH_VU 
	WHERE MaDV = @MADV;
	RETURN @THANHTIEN_SD_DV;
END;
GO

SELECT DP.MaDatPhong, SD.MaDV, DV.TenDV, SD.SoLuong, DV.DonGia, dbo.fn_1LAN_SD_DV(SD.MaDV, SD.SoLuong) AS THANHTIEN_SUDUNG
FROM DAT_PHONG DP
INNER JOIN SU_DUNG_DV SD 
ON DP.MaDatPhong = SD.MaDatPhong
INNER JOIN DICH_VU DV 
ON DV.MaDV = SD.MaDV;
GO

-- BT16: 
CREATE PROCEDURE TINH_HINH_KHAITHAC_PHONG @MALOAIPHONG VARCHAR(10)
AS 
BEGIN 
	SELECT COUNT(DISTINCT P.SoPhong) AS SOPHONG
		, COUNT(DP.MaDatPhong) AS SOPHIEUDATPHONG
	FROM LOAI_PHONG LP 
	INNER JOIN PHONG P 
	ON LP.MaLoaiPhong = P.MaLoaiPhong
	LEFT JOIN DAT_PHONG DP
	ON DP.MaPhong = P.MaPhong
	WHERE LP.MaLoaiPhong = @MALOAIPHONG;

	SELECT P.SoPhong, COUNT(DP.MaDatPhong) AS SOPHIEUDATPHONG
	FROM LOAI_PHONG LP
	INNER JOIN PHONG P 
	ON LP.MaLoaiPhong = P.MaLoaiPhong
	LEFT JOIN DAT_PHONG DP
	ON DP.MaPhong = P.MaPhong
	WHERE LP.MaLoaiPhong = @MALOAIPHONG
	GROUP BY P.SoPhong;
END;
GO

-- BT17: 
CREATE PROCEDURE KH_SD_DV_CAO @SOLUONGDV_TOITHIEU INT, @SOTIENDV_TOITHIEU DECIMAL(12,2)
AS 
BEGIN 
	SELECT 'SO LUONG KHACH HANG THOA DK' AS NOIDUNG
		, COUNT(*) AS SOLUONGKH_THOA_DK
	FROM 
	(SELECT DP.MaKH
	FROM DAT_PHONG DP 
	INNER JOIN SU_DUNG_DV SD 
	ON DP.MaDatPhong = SD.MaDatPhong
	INNER JOIN DICH_VU DV
	ON DV.MaDV = SD.MaDV
	GROUP BY DP.MaKH
	HAVING SUM(SD.SoLuong) >= @SOLUONGDV_TOITHIEU AND SUM(DV.DonGia * SD.SoLuong) >= @SOTIENDV_TOITHIEU) AS TESTS;

	SELECT KH.MaKH, KH.HoTen
		, SUM(SD.SoLuong) AS TONGSOLUONGDV
		, SUM(DV.DonGia * SD.SoLuong) AS TONGTIENDV 
	FROM DAT_PHONG DP 
	INNER JOIN KHACH_HANG KH
	ON KH.MaKH = DP.MaKH
	INNER JOIN SU_DUNG_DV SD 
	ON DP.MaDatPhong = SD.MaDatPhong
	INNER JOIN DICH_VU DV
	ON DV.MaDV = SD.MaDV
	GROUP BY KH.MaKH, KH.HoTen
	HAVING SUM(SD.SoLuong) >= @SOLUONGDV_TOITHIEU AND SUM(DV.DonGia * SD.SoLuong) >= @SOTIENDV_TOITHIEU;
END;
GO

-- BT18: 
CREATE PROCEDURE PROCE_KETHOP_PRO_FUNC @MAKH VARCHAR(10)
AS 
BEGIN 
	SELECT 'SO LUONG DAT PHIEU CUA KHACH HANG ' + @MAKH AS NOIDUNG
		, COUNT(*) AS SOLUONGPHIEUDAT 
	FROM DAT_PHONG DP 
	INNER JOIN KHACH_HANG KH 
	ON DP.MaKH = KH.MaKH
	WHERE KH.MaKH = @MAKH; 

	SELECT DP.MaDatPhong, dbo.fn_TONGTIENDV(DP.MaDatPhong) AS TONGTIENDICHVU
	FROM DAT_PHONG DP 
	INNER JOIN KHACH_HANG KH 
	ON DP.MaKH = KH.MaKH
	WHERE KH.MaKH = @MAKH; 
END;
GO

-- BT19: 
-- Nghiệp vụ này sẽ liên quan đến việc mình sẽ tạo một hàm function với tham số là mã đặt phòng và mình trả về giá trị doanh thu đến từ việc sử dụng phòng của mã đặt phòng đó
-- Lưu ý: tính thành tiền được bằng cách nhân đơn giá với số ngày.
CREATE FUNCTION fn_REVENUE_MDP(@MADATPHONG VARCHAR(10), @SONGAYLUUTRU INT)
RETURNS DECIMAL(12, 2)
AS 
BEGIN 
	DECLARE @REVENUE DECIMAL(12, 2); 
	SELECT @REVENUE = SUM(LP.DonGia * @SONGAYLUUTRU)
	FROM DAT_PHONG DP 
	INNER JOIN PHONG P
	ON DP.MaPhong = P.MaPhong
	INNER JOIN LOAI_PHONG LP 
	ON LP.MaLoaiPhong = P.MaLoaiPhong
	WHERE DP.MaDatPhong = @MADATPHONG;
	RETURN @REVENUE;
END;
GO

-- Ví dụ với khách hàng KH01 ở bài tập 14S